#-----------------------------------------------------------------------------------------
# CS249 -- Spring 2014 -- Course Project clustering
#-----------------------------------------------------------------------------------------

not.installed = function(package_name)  !is.element(package_name, installed.packages()[,1])
if (not.installed("scatterplot3d")) install.packages("scatterplot3d")
library(scatterplot3d)


pdf("LSIplots.pdf", 8,8)   ##### put the plots generated by this script into LSIplots.pdf

#-----------------------------------------------------------------------------------------
# Generate LSI and MDS plots for each of the .csv files
#-----------------------------------------------------------------------------------------

for (filestem in c("datatypes_and_disciplines", "datatypes", "disciplines")) {

   filename = paste(filestem,".csv",sep="")
   data = read.csv(filename, header=TRUE)

   numeric_data = data.matrix(data[,2:ncol(data)])
   rownames(numeric_data) = data[,1]

   s = svd(numeric_data);
   sigma = s$d
   U = s$u
   V = s$v
   S = diag(sigma)

   u1 = U[,1];  u2 = U[,2]; u3 = U[,3]  # axes for students
   v1 = V[,1];  v2 = V[,2]; v3 = V[,3]  # axes for topics

   uv1 = c(u1,v1); uv2 = c(u2,v2); uv3 = c(u3,v3);

   xrange = range(uv1) * 1.18 + 0.021
   yrange = range(uv2) * 1.05
   zrange = range(uv3) * 1.05

   #-----------------------------------------------------------------------------------------
   # plot the 2D LSI eigen-projection of the data
   #-----------------------------------------------------------------------------------------

   plot(   u1, u2, pch=20, col="blue", xlim=xrange, ylim=yrange,
                   xlab = "coordinate on 1st eigenvector", ylab = "coordinate on 2nd eigenvector",
                   main = paste(filestem, "-- LSI projection of Students and Topics") )
   abline( h=0, col="gray" )  # add x-axis line
   abline( v=0, col="gray" )  # add y-axis line
   points( v1, v2, pch=20, col="red" )
   text(   u1, u2, rownames(numeric_data), col="blue", pos=2, offset=0.25, cex=0.50 )
   text(   v1, v2, colnames(numeric_data), col="red",  pos=4, offset=0.25, cex=0.40 )

   legend( "topleft", c("Student", "Topic"), cex=0.85, col=c("blue","red"), pch=c(20,20))

   #-----------------------------------------------------------------------------------------
   # plot the 3D LSI eigen-projection of the data
   #-----------------------------------------------------------------------------------------

   nu = length(u1)
   nv = length(v1)
   s3d = scatterplot3d( uv1, uv2, uv3, pch=20,
                        xlim=xrange*0.75, ylim=yrange*0.75, zlim=zrange*0.75,
                        color="lightgray", # color=c( rep("red",nu), rep("blue",nv) ),
                        xlab = "coordinate on 1st eigenvector",
                        ylab = "coordinate on 2nd eigenvector",
                        zlab = "coordinate on 3rd eigenvector",
                        main = paste(filestem, "-- 3D LSI projection of Students and Topics") )
   s3d$points3d( v1,v2,v3, col="red",  pch=16 )
   s3d$points3d( u1,u2,u3, col="blue", pch=16 )
   s3d.coords = s3d$xyz.convert(uv1, uv2, uv3)
   text( s3d.coords$x[1:nu], s3d.coords$y[1:nu],
         rownames(numeric_data), col="blue", pos=2, offset=0.25, cex=0.50 )
   text( s3d.coords$x[(nu+1):(nu+nv)], s3d.coords$y[(nu+1):(nu+nv)],
         colnames(numeric_data), col="red",  pos=4, offset=0.25, cex=0.40 )

   #-----------------------------------------------------------------------------------------
   # plot the LSI scree plot for the data
   #-----------------------------------------------------------------------------------------

   plot( sigma, type="l", col="red",
           xlab = "singular value number", ylab = "singular value",
           main = paste(filestem, "-- LSI singular values (scree plot)") )
   points( sigma, col="blue", pch=20 )

   legend("topright", paste( sprintf("%3d",1:min(nu,nv)), ": ", sprintf("%8.3f", sigma[1:min(nu,nv)])),
           text.col="blue3", box.col="red", cex=0.5 )

   #-----------------------------------------------------------------------------------------
   # plot the MDS embedding of the data
   #-----------------------------------------------------------------------------------------

   Dist = dist( numeric_data, method="manhattan" )

   loc = cmdscale(Dist) 
   xrange = range(loc[,1]) * 1.2 + 1
   yrange = range(loc[,2]) * 1.05

   plot( loc[,1], loc[,2], pch=20, xlim=xrange, ylim=yrange,
          xlab = "MDS 1st coordinate", ylab = "MDS 2nd coordinate",
          main=paste(filestem, "-- Multi-Dimensional Scaling embedding"), col="green4" )
   abline( h=0, col="gray" )  # add x-axis line
   abline( v=0, col="gray" )  # add y-axis line
   text( loc[,1], loc[,2], rownames(loc), col="green4", pos=4, offset=0.25, cex=0.50 )

}

dev.off()     #####  terminate plotting
