opar = par(mfrow=c(1,2), mar=c(4,2,3,1), mgp=c(2,1,0))
mu = exp(2)
mulog = log(mu)
sigma = 1
sigmalog = (1)
lnorm = function(x) dlnorm(x, meanlog=mulog, sdlog=sigmalog)

curve( lnorm, exp(-1.5), exp(4.0), col="forestgreen", main=expression(lognormal ~ distribution ~ with * "  " * mu * " = " * 2 * ",  " * sigma * " = " * 1), ylim = c(0,0.1), cex.axis=0.65, cex.main=0.85, ylab="", cex.lab = 0.75, lwd = 2, col.main="darkgreen", col.lab="gray10" )
x = exp(mulog)
points( c(x,x), c(0,lnorm(x)), col="gray25", type="l")
text( x, lnorm(x), expression( median * "  " * at * "  " * x * "  =  " * e^mu * "  =  " * e^2), col="gray25", pos=4, offset=0.5, cex=0.75)
x = exp(mulog + sigma^2/2)
points( c(x,x), c(0,lnorm(x)), col="gray25", type="l")
text( x, lnorm(x), expression( mean * "  " * at * "  " * x * "  =  " * e^{mu ~ + ~ sigma^2/2} * "  =  " * e^2.5), col="gray25", pos=4, offset=0.5, cex=0.75)
x = exp(mulog - sigma^2)
points( c(x,x), c(0,lnorm(x)), col="gray25", type="l")
text( x, lnorm(x), expression( mode * "  " * at * "  " * x * "  =  " * e^{mu ~ - ~ sigma^2} * "  =  " * e^1), col="gray25", pos=4, offset=0.5, cex=0.75)
mtext( expression( f(x) ~ "  =  " ~ g(log(x))/x ~ "  =  " ~  1/(sqrt(2*pi) * sigma) ~ " " ~ exp(-1/2 ~ ((log(x)-mu)/sigma)^2) ~ " / " ~ x), col="gray25", side=3, line=0.2, cex=0.55)

transformed_lnorm = function(x) lnorm(exp(x)) * exp(x)
curve( transformed_lnorm, (-0.5), (4.5), col="forestgreen", main=expression(normal ~ distribution ~ with * "  " * mu * " = " * 2 * ",  " * sigma * " = " * 1), ylim = c(0,0.47), cex.axis=0.65, cex.main=0.85, xlab="z" , ylab="", cex.lab = 0.75, lwd = 2, col.main="darkgreen", col.lab="gray10")
x = (mulog)
points( c((x),(x)), c(0,transformed_lnorm(x)), col="gray25", lwd=1.5, type="l")
text( (x), transformed_lnorm(x), expression( "mean = median = mode at  " * z * "  =  " * mu * "  =  " * 2), col="gray25", pos=3, offset=0.25, cex=0.75)
# text( (x), transformed_lnorm(x), expression( median ), col="gray25", pos=4, offset=0.75, cex=0.7)
# x = exp(mulog + sigma^2/2)
# points( c(log(x),log(x)), c(0,transformed_lnorm(x)), col="gray25", type="l")
# text( log(x), transformed_lnorm(x), expression( mean ), col="gray25", pos=4, offset=0.75, cex=0.7)
# x = (mulog - sigma^2)
# points( c((x),(x)), c(0,transformed_lnorm(x)), col="gray25", type="l")
# text( log(x), transformed_lnorm(x), expression( mode ), col="gray25", pos=4, offset=0.75, cex=0.7)
mtext( expression( g(z) ~ " = " ~ f(e^z) ~ " " ~ e^z ~ "    [result of the change of variables  z = log(x)]"), col="gray25", side=3, line=0.2, cex=0.55)
par(opar)
